package modelo.entidad;
// Generated 9/11/2021, 6:05:15 p.m. by Hibernate Tools 4.3.1



/**
 * Medicos generated by hbm2java
 */
public class Medicos  implements java.io.Serializable {


     private int idMedico;
     private String nombre;
     private int sala;
     private String especialidad;

    public Medicos() {
    }

    public Medicos(int idMedico, String nombre, int sala, String especialidad) {
       this.idMedico = idMedico;
       this.nombre = nombre;
       this.sala = sala;
       this.especialidad = especialidad;
    }
   
    public int getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(int idMedico) {
        this.idMedico = idMedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getSala() {
        return this.sala;
    }
    
    public void setSala(int sala) {
        this.sala = sala;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }




}


